### ISSUE TITLE
Does this project support zcu102?

### ISSUE THREAD

**Issue by Wlfc912** [OSCPU/NutShell#106]
Under `Nutshell/fpga/board`, there are only PXIe, axu3cg, and zynq available, while in README.md under `Nutshell/fpga/boot`, it seems that zcu102 is supported as well. But when I tried to generate BOOT.BIN, I'm again restricted to the aforementioned 3 boards. 

So is the case as discussed in [this issue](https://github.com/OSCPU/NutShell/issues/13), that for any board other than PXIe, axu3cg and zynq, we will have to configure everything ourselves? Or is zcu102 somehow supported? Also, if we have to configure the files ourselves, are there any suggestions or tips that you can provide?

**Comment by songwennuan123** [comment]
是否有完整的在其他板子上实现移植nutshell的步骤，我在AX7350上也无法完成移植，卡在了内核的启动上
