### ISSUE TITLE
 请问如何在zedboard上运行？

### ISSUE THREAD

**Issue by Aerotic** [OSCPU/NutShell#13]
是直接按AXU3CG配置生成的各种文件直接用于zedboard就可以了么

**Comment by wakafa1** [comment]
Aerotic 你好，
很抱歉，我们目前的工程暂时没有对 zedboard 进行适配，你可以参照 AXU3CG 的 vivado 工程设计自己的 block design，然后对 NutShell 核心做对应的配置修改。需要匹配的部分主要包括内存地址、mmio地址、ResetVector和外部中断个数等。

**Comment by sashimi-yzh** [comment]
@Aerotic 你好, zedboard和pynq的fpga型号是一样的, 原理上应该可以使用项目中pynq的配置来运行zedboard, 但我们手上没有zedboard的开发板, 无法进行尝试, 所以是否能行并不确定.

**Comment by Aerotic** [comment]
> @Aerotic 你好, zedboard和pynq的fpga型号是一样的, 原理上应该可以直接使用项目中pynq的配置来运行zedboard, 但我们手上没有zedboard的开发板, 无法进行尝试, 所以是否能行并不确定.
> 
> 如果你对fpga流程比较熟悉, 也可以根据pynq的配置将项目移植到zedboard中.

好的 我试试 谢谢回复
