### ISSUE TITLE
Xufzz使用

### ISSUE THREAD

**Issue by wyz-icer** [OSCPU/NutShell#185]
您好！
在工程提供的workflow内
使用 集成xfuzz流程
Nutshell 编译生成 xfuzz 可执行文件后
![image](https://github.com/OSCPU/NutShell/assets/30771839/ae5a6a5b-d82b-4c13-9511-b2b631b4f489)

提供的执行命令：
./build/fuzzer -v -- ./ready-to-run/microbench.bin -e 0

依据 --help 输出的支持参数 没有对 “--”的解析
这里 “--” “./ready-to-run/microbench.bin” 这样指定 的含义怎么解释
实际按执行命令可以执行

**Comment by poemonsense** [comment]
See https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean

Closed because this issue is for xfuzz instead of NutShell
