### ISSUE TITLE
Will you maintain NutShell all the time?

### ISSUE THREAD

**Issue by hyf6661669** [OSCPU/NutShell#38]
你好，请问你们会一直更新这个项目么，还是学生毕业之后就停止维护了？我之前也从事过RISC-V CPU的设计工作，如果一直有人来更新的话，我希望有机会能和维护人认识一下，也许可以加个微信/qq交流一下想法？

**Comment by wakafa1** [comment]
@hyf6661669 你好，很高兴你对我们的项目感兴趣，我们会长期维护该项目的，也非常欢迎你可以一起参与进来.
可以加这个微信号交流：13063930225
