### ISSUE TITLE
构建工程出现问题

### ISSUE THREAD

**Issue by sazczmh** [OSCPU/NutShell#44]
请问，我已经安装了mill，可是仍然出现下述的构建问题

![image](https://user-images.githubusercontent.com/49888860/101139059-efe2d700-364b-11eb-8c8c-dca85786ccaa.png)

是因为版本不对应吗？我的版本是0.9.3

![image](https://user-images.githubusercontent.com/49888860/101139788-fe7dbe00-364c-11eb-9194-3cf159b20e5e.png)

**Comment by AugustusWillisWang** [comment]
已确认新版本的mill无法正常构建工程, 将在下次更新框架时处理.

目前版本下, 版本为 0.6.3 / 0.7.4 的`mill`已知可用.

**Comment by sazczmh** [comment]
> 已确认新版本的mill无法正常构建工程, 将在下次更新框架时处理.
> 
> 目前版本下, 版本为 0.6.3 / 0.7.4 的`mill`已知可用. 0.8 以后的版本暂不可用.

**Comment by sazczmh** [comment]
![image](https://user-images.githubusercontent.com/49888860/101167159-74e1e680-3674-11eb-88b9-1230c6bff0e0.png)

多谢，已经成功生成了vivado工程
