### ISSUE TITLE
请问如何用riscv-pk和linux内核源码制作出一个RV_BOOT.bin

### ISSUE THREAD

**Issue by whysodangerous** [OSCPU/NutShell#48]
请问能否提供一下编译linux内核源码时的config配置和编译选项，以及riscv-pk的配置情况。目前我只能通过riscv-pk和Linux内核源码得到一个bbl镜像，无法得到如文档中所说的“名字默认的RV_BOOT.bin"。

**Comment by wakafa1** [comment]
你好，这边建议使用我们预编好的内核镜像，在 NutShell/fpga/boot/pynq/RV_BOOT.bin；如果想要自行生成，Linux 配置请使用 riscv-linux/arch/riscv/configs/fpga_defconfig，其中一些选项需要根据实际情况酌情修改；riscv-pk 方面，请在 riscv-pk/dts 中使用合适的设备树，然后 make 即可，最终在 riscv-pk/build 目录下会得到 bbl.bin 文件，即为我们想要的 RV_BOOT.bin（名字默认的意思是后续的流程会直接使用“RV_BOOT.bin”文件名，因此需要手动将 bbl.bin 重命名为 RV_BOOT.bin）

**Comment by songwennuan123** [comment]
我在FPGA上启动时启动流程卡在了
Reset RISC-V core.
请问这有可能时什么导致的？

![Uploading 1703817893235.png…]()
