### ISSUE TITLE
Is the NutShell core out-of-order?

### ISSUE THREAD

**Issue by JaewonHur** [OSCPU/NutShell#57]
As the title, is the nutshell core out-of-order machine?

I found lots of commit messages containing the key word, 'out of order',
but I could not found any official information describing the feature.

Thanks in advance.

**Comment by AugustusWillisWang** [comment]
NutShell itself is a in-order core.

A out-of-order core based on NutShell (Argo) shares NutShell's infrastructure. Its source code is also in NutShell repo. 'out of order' commits is about that. 

Note that the out-of-order core has only been tested on FPGA. It is provided without any warranties.

**Comment by JaewonHur** [comment]
Thanks
