### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by AdityaCyberSafe** [OSCPU/NutShell#58]
Hi,
Has the project been cancelled?
Because it shows that the latest commit was on 19 july.
Thanks

**Comment by sashimi-yzh** [comment]
No. Welcome to contribute!

**Comment by AdityaCyberSafe** [comment]
Hi, then why is it that the last commit was on 19 July??
Thanks in advance

**Comment by AugustusWillisWang** [comment]
Master branch is for stable design only. `View all branches` to see the latest update.
