### ISSUE TITLE
Nutshell接入difftest出现的错误

### ISSUE THREAD

**Issue by youonlylooktwice** [OSCPU/NutShell#60]
你好！
我在参考https://github.com/OSCPU/ysyx/issues/8  中接入difftest框架时出现了问题，按照步骤修改，在运行指令  mill -i __.test.runMain top.TopMain -td ./build 构建 SimTop.v 时出现问题，报错如下：
![image](https://user-images.githubusercontent.com/94279813/142747572-9bbb8dcf-dda3-4e70-ad4e-e5e70a9308a4.png)
请问您知道是哪里出错了吗？

**Comment by wakafa1** [comment]
请仔细查看报错信息：内容显示 TopMain.scala:41 出错，对应源码很容易发现是什么问题；此后建议再阅读一下 NutShell 的 Makefile 以解决问题
