### ISSUE TITLE
如何去除difftest和nemu直接跑linux.bin或者microbench.bin？

### ISSUE THREAD

**Issue by trueif** [OSCPU/NutShell#65]
我make emu能过，但是我做了一些改动，把microbench.bin的内容写入了ram.v里面，想试图直接从RAM里面启动microbench或者linux（有点类似RISC_SPM的玩法）。但是发现make emu依赖了difftest和nemu（CPPFLAGS=-DREF_SO=\\\"./ready-to-run/riscv64-nemu-interpreter-so\\\"）。

求问有什么方法绕过difftest和nemu吗？

**Comment by AugustusWillisWang** [comment]
运行 emu 的时候可以添加 --no-diff 参数关掉和 NEMU 的实时对比

**Comment by trueif** [comment]
> 

谢谢。这个功能貌似只有香山有。果壳没有。我试试香山去。

**Comment by AugustusWillisWang** [comment]
现在果壳和香山使用的是相同的仿真顶层, 两者 emu 的参数都是一样的

**Comment by trueif** [comment]
> 现在果壳和香山使用的是相同的仿真顶层, 两者 emu 的参数都是一样的

用了新的版本，确实可以--no-diff了。谢谢！
