### ISSUE TITLE
如何用nexus-am编译出可以在nutshell-pynq上运行的裸机程序

### ISSUE THREAD

**Issue by Wwy111** [OSCPU/NutShell#75]
我将nexus-am中的物理起始地址以及uartlite mmio地址改为pynq setting中的0x60000000和0xe0000000，并把/fpga/resource/fsbl-loader.c中的文件名改成了所需文件名。将重新生成的BOOT.BIN和所需.bin文件放入sd卡中，但是fpga没有任何输出。想请问还需要对nexus-am代码做什么改动？

**Comment by wakafa1** [comment]
pynq 使用 standalone 模式启动，他的串口协议是 xuartps 而不是 uartlite；请参考 https://github.com/OSCPU/riscv-pk/blob/zynq-standalone/dts/zynq-standalone.dtsi#L13
