### ISSUE TITLE
关于mem的地址分配

### ISSUE THREAD

**Issue by wuyouniyanhu** [OSCPU/NutShell#97]
您好，
       关于内存接口的地址范围存在一些疑问：

1、请问现在的nutshell是否有对mem访存地址范围的限制（32位宽，4GB之内）？
2、可以生成多个mem接口吗？
3、在src/main/scala/top/Settings.scala中我看到有MemMapRegionBits的设置，是否指em的地址范围必须是2^n对齐的，同时需要是一段连续的内存地址空间？如果设计需要用两端不连续的地址范围，应该如何设置呢

祝好！

**Comment by wuyouniyanhu** [comment]
若MemMapRegionBits设为0，那么地址空间会将所有除MMIO与内部外设以外的全部空间给到mem吗

**Comment by AugustusWillisWang** [comment]
可以根据您的需要自行调整代码，下面的这些部分负责 mem 相关物理地址的映射：

https://github.com/OSCPU/NutShell/blob/403800bb12689aa39617192bac3d351974ee123f/src/main/scala/system/NutShell.scala#L93

https://github.com/OSCPU/NutShell/blob/39677ff7498c2c5fb6ada46f8c1742d12ec7b72f/src/main/scala/bus/simplebus/AddressMapper.scala#L25-L36
